language: ruby
cache: bundler
sudo: required
dist: trusty
addons:
    postgresql: "9.6"
    chrome: stable

services:
    - postgresql
    - redis-server

rvm:
  - 2.6.2

env:
  - DB=postgres

before_script:
  - psql -c 'create database crowdai_test;' -U postgres
  - bundle exec chromedriver-update 2.46

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - bundle exec rake parallel:setup
  - bundle exec rake parallel:spec

branches:
  only:
    - master
